name: Sync frontend branch with main

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out deployment branch
        uses: actions/checkout@v4

      - name: Set bot name and email
        run: |
          git config --global user.name "Otto"
          git config --global user.email "kaylale2014@gmail.com"

      - name: Checkout main and frontend
        run: |
          git fetch
          git checkout main
          git checkout frontend

      - name: Sync frontend with main
        run: |
          git rebase frontend
          git push origin frontend
